config/routes.rb
Rails.application.routes.draw do
   
  root 'pages#home'
  
  get 'sessions/new'

  get 'users/new'

  get 'users/index'

  get 'users/show'

  get '/sign_up', to: 'users#new'

  get '/login',to: 'sessions#new'

  post '/login',to: 'sessions#create'

  get '/logout',to: 'sessions#destroy'
  
  get '/about',to: 'pages#about'


  
  resources :checkins

  resources :users

  namespace :admin do
    resources :rooms
    resources :guests
    resources :bookrooms
    resources :roomtypes
    get '/bill',to: 'bookrooms#bill'
    post '/bill',to: 'bookrooms#bill'
    get '/checkout',to: 'bookrooms#checkout'
    get '/checkin',to: 'bookrooms#checkin'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
  has_many :lineitems,dependent: :destroy,:inverse_of => :checkin
  accepts_nested_attributes_for :lineitems,
  :reject_if => :all_blank, :allow_destroy => true

   enum status: [ :pending,:staying,:finish ]
  
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
	belongs_to :checkin
	has_many :lineitem_details, dependent: :destroy,:inverse_of => :lineitem
	accepts_nested_attributes_for :lineitem_details,
	:reject_if => :all_blank, :allow_destroy => true
end

app/models/lineitem_detail.rb
class LineitemDetail < ApplicationRecord
  belongs_to :lineitem 
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/permission.rb
class Permission < ApplicationRecord
	has_many :users
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :roomtype
  validates :room_code,  presence: true 
  mount_uploader :avatar, PictureUploader
end

app/models/roomtype.rb
class Roomtype < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	validates :name,presence: true,length: {maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,presence: true,length: {maximum:50},
	          format: {with: VALID_EMAIL_REGEX},
	          uniqueness: {case_sensitive: false }
	has_secure_password	

	belongs_to :permission
	has_many :checkins

	

end

app/controllers/admin/roomtypes_controller.rb
class Admin::RoomtypesController < ApplicationController
	def new
      @roomtype=Roomtype.new
    end
    def create
       @roomtype=Roomtype.new (room_type_params)
       if @room_type.save
       	flash[:success]="Room type created successfully"
       	redirect_to admin_roomtypes_path
       else
       	render 'new'
       end
    end
    def index
    	@roomtypes=Roomtype.paginate(page: params[:page],per_page: 4)
    end

    def edit
    	@roomtype=Roomtype.find_by(id: params[:id])
    end
    def update
    	@roomtype=Roomtype.find_by(id: params[:id])
    	if @roomtype.update_attributes(room_type_params)
    		flash[:success]="Room type update successfully"
    		redirect_to admin_roomtypes_path
    	else
    		render 'edit'
    	end
    end
    def destroy
      Roomtype.find(params[:id]).destroy
      redirect_to admin_roomtypes_path
    end

    private
    def room_type_params
    	params.require(:roomtype).permit(:name,:price,:description)
    end
end

app/controllers/bookrooms_controller.rb
class BookroomsController < ApplicationController
	def index
		@rooms=Room.all
    end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :logged_in_user, only: [:index, :create]
	def index
		@rooms=Room.all
  end
  def new
    	@checkin=current_user.checkins.build
    	@checkin.lineitems.build
    	#@lineitem_details=@lineitem.lineitem_details.build
    	@checkin.lineitems.each do |lineitem|
          lineitem.lineitem_details.build
      end
     	@room=Room.find_by(id: params[:room_id])
  end

  def create
      #khong phải là giải pháp cuối cùng =>
      #1,chưa thực hiện checkin bao giờ 
      #2.check in cuối cùng đã kết thúc
     
     #debugger
      #if  current_user.checkins.exists? && current_user.checkins.where("status = ?",0).exists?

          #current_check_in.lineitems.create checkin_params1
          # current_checkin=current_user.checkins.last
           #current_checkin.lineitems.create()
           

           # current_checkin.lineitems.create(room_code: params[:checkin][:lineitems_attributes]["0"][:room_code],
           #                   startdate: params[:checkin][:lineitems_attributes]["0"][:fromdate],
           #                   fromdate: params[:checkin][:lineitems_attributes]["0"][:fromdate])
          
          

           # n = params[:checkin][:lineitems_attributes]["0"][:lineitem_details_attributes].count
           # for i in 1..n

          #params[:checkin][:lineitems_attributes]["0"][:lineitem_details_attributes].each do |f| 
         
               
          #end


      #else
          @checkin =Checkin.create checkin_params
           # @checkin=current_user.checkins.last
           # @checkin.lineitems.create checkin_params1

     # end
       #debugger
       redirect_to checkins_path
       #end
  end

    private

    def checkin_params
       params.require(:checkin).permit(:telephone,:user_id,:description,
        lineitems_attributes:[:id,:room_code,:startdate,:fromdate,:numberofperson,
        lineitem_details_attributes:[:id,:nameguest,:identification,:address]])
       

     # debugger
    end

     def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end

    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def  home
	end
	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user=User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
         login user
         flash[:success]="Welcome to Plaza Hotel"
         if user.permission.role == 1
          redirect_to admin_rooms_path
         else
          redirect_to  checkins_path
         end 
  	else
  		flash[:danger]='Invalid emails/password '
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    	@users = User.paginate(page: params[:page])
    end

	def show
		@user=User.find(params[:id])
		@entries = @user.entries.paginate(page: params[:page])
	end

	def new
		@user=User.new
	end

	def create
		@user=User.new(user_params)
		@user.permission_id=6
		if @user.save
			login @user
			flash[:success] ="Welcome to the Plaza Hotel!"
			redirect_to checkins_path
		else
			render 'new'
		end
	end

	def edit
		@user=User.find(params[:id])
	end

    def update
    	@user=User.find(params[:id])
    	if @user.update_attributes(user_params)
    		flash[:success]="Profile updated"
    		redirect_to @user
    	else
    		render 'edit'
    	end
    end

    def user_params
	  	params.require(:user).permit(:name,:email,:password,
	  		:password_confirmation)
	end

end

app/helpers/admin/roomtypes_helper.rb
module Admin::RoomtypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def hash_payment id
	  user=User.find_by_id(2)  
      hash_payment=Hash.new
       all_checkin=user.checkins
       all_checkin.each  do |checkin|
       hash_payment[:room_code]=checkin.lineitems.first.room_code
       hash_payment[:numberofperson]=3
       end     
    end
    def get_corresspond_lineitem id
        checkin=Checkin.find_by(id:id)
        checkin.lineitems.first
    end

    def get_corresspond_roomtype name
        room=Room.find_by(room_code:name)
        room.roomtype
    end

    def get_time_booking startdate,fromdate
        t=(fromdate - startdate)/3600
        t.to_i
    end
    def totalpay
    	
    end
     
end

app/helpers/bookrooms_helper.rb
module BookroomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# log in the given user
	def login(user)
		session[:user_id]=user.id
	end

	#Returns the current logged-in user
	def current_user
		@current_user ||=User.find_by(id: session[:user_id])
	end
    #check if user login
	def logged_in?
		!current_user.nil?
	end
    #logout out the current user
	def log_out
		session.delete(:user_id)
		@current_user=nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/roomtypes/_form.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <tiles:putAttribute name="content">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= yield(:title) %></h1>
      </div>
    </div>

    <%= form_for [:admin,@roomtype],html: {class: "form-horizontal",multipart: true} do |r| %>
       <%= render 'shared/error',object: @roomtype %>
        <div class="form-group">
        <label class="col-lg-2 control-label">Tên</label>
        <div class="col-lg-8">
           <%= r.text_field :name,class: "form-control input-medium" %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Giá 1 giờ</label>
        <div class="col-lg-8">
           <%= r.text_field :price,class: "form-control input-medium" %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Mô tả</label>
         <div class="col-md-8">
          <%= r.text_area :description,class: "form-control input-medium",rows: 10 %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label"></label>
        <div class="col-md-8">
          <%= r.submit yield(:button_text),class: "btn btn-primary" %>
          <span></span>
          <a href="" class="btn btn-default">Hủy</a>
        </div>
      </div>
    </form>
    <% end %>


  </tiles:putAttribute>

  <tiles:putAttribute name="javascript-source">
</tiles:putAttribute>

</tiles:insertTemplate>

</div>
</div>

</div>

app/views/admin/roomtypes/edit.html.erb
<% provide(:title,"Sửa thông tin loại phòng") %>
<% provide(:button_text,"Sửa") %>
<%= render 'form' %>

app/views/admin/roomtypes/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <tiles:insertAttribute name="content"></tiles:insertAttribute>
    <tiles:putAttribute name="content">
    <link href="/hanashop/templates/resource/datatable-bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="/hanashop/templates/resource/resources/datatable-responsive/css/dataTables.responsive.css" rel="stylesheet" />
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Danh sách loại phòng</h1>
      </div>
    </div>
    <p>
      <%= link_to new_admin_roomtype_path,class: "btn btn-success" do %>
        Thêm<i class="fa fa-plus"></i>
      <% end %>
    </p>
    <table class="table table-striped table-bordered table-hover" id="dataTables-dsSanPham">
      <thead>
        <tr>
          <th align="center">Name</th>
          <th align="center">Giá 1 giờ (VNĐ)</th>
          <th align="center">Mô tả</th>
          <th align="center">Chức năng</th>
        </tr>
      </thead>
      <tbody id="tbl-body">
        <% @roomtypes.each do |r| %>
        <tr> 
          <td align="center"><%= r.name %></td>
          <td align="center"><%= r.price %></td>
          <td align="center"><%= r.description %></td>
          <td align="center">
             <input type="hidden" id="hidden-maSanPham" value="" />
             <%= link_to edit_admin_roomtype_path(r),class: "btn btn-default" do %>
              <i class="fa fa-edit"></i>
             <% end %>
             <%= link_to admin_roomtype_path(r), id: "btn-xoa",class: "btn btn-default",method: :delete,data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-remove"></i>
              <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div align="center">
     <%= will_paginate %>
    </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
            <div class="modal-content">
              <form id="form-xoa"
              action=""
              method="post">
              <input id="modal-hidden-maSanPham" type="hidden" value=""
              name="maSanPham" />
              <div class="modal-header">
                <a href="#" data-dismiss="modal" aria-hidden="true" class="close">xóa</a>
                <h3>Xóa</h3>
              </div>
              <div class="modal-body">
                <p>Bạn có chắc chắn xóa thông tin này không?</p>
              </div>
              <div class="modal-footer">
                <button type="submit" id="btnYes" class="btn btn-danger">Có</button>
                <button type="button" data-dismiss="modal" aria-hidden="true"
                class="btn btn-secondary">Không</button>
              </div>
            </form>
          </div>
        </div>
      </div>


    </tiles:putAttribute>
    <tiles:putAttribute name="javascript-source">
    </tiles:putAttribute>
</tiles:insertTemplate>
</div>
</div>
</div>

app/views/admin/roomtypes/new.html.erb
<% provide(:title,"Thêm thông tin loại phòng") %>
<% provide(:button_text,"Thêm") %>
<%= render 'form' %>