config/routes.rb
Rails.application.routes.draw do
   
  root 'pages#home'
  
  get 'sessions/new'

  get 'users/new'

  get 'users/index'

  get 'users/show'

  get '/sign_up', to: 'users#new'

  get '/login',to: 'sessions#new'

  post '/login',to: 'sessions#create'

  get '/logout',to: 'sessions#destroy'
  
  get '/about',to: 'pages#about'


  
  resources :checkins

  resources :users

  namespace :admin do
    resources :rooms
    resources :guests
    resources :bookrooms
    resources :roomtypes
    get '/bill',to: 'bookrooms#bill'
    post '/bill',to: 'bookrooms#bill'
    get '/checkout',to: 'bookrooms#checkout'
    get '/checkin',to: 'bookrooms#checkin'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/bookrooms_controller.rb
class Admin::BookroomsController < ApplicationController
	def index
		#@bookrooms=Checkin.distinct.paginate(page: params[:page],per_page: 2)
		@bookrooms = Checkin.group(:user_id).paginate(page: params[:page],per_page: 2)
	end
    
    def checkin
    	#get params user_id
        @user=User.find_by_id(params[:user_id]) 
        #get all checkin       
        @checkins=@user.checkins   
        #update status   
    	@checkins.each do |c|
          c.staying!
	    end
	    redirect_to admin_bookrooms_path
    end

	def show
        #get params user_id
        @user=User.find_by_id(params[:user_id]) 
        #get all checkin       
        @checkins=@user.checkins.   
	end

	def checkout
        @user_id = params[:user_id]
        #=> tới trang phương thức thanh toán
        
	end
	def destroy
		#destroy checkin
	end

	def bill
        #get params paymethod
        @paymethod=params[:pay]
        #get params user_id
		@user=User.find_by_id(params[:user_id])      
        #Save vao payment va thống kê

        #show view
		@checkins=@user.checkins
		#update status thành finish
		@checkins.each do |c|
          c.finish!
	    end

       
    end



	
end

app/controllers/bookrooms_controller.rb
class BookroomsController < ApplicationController
	def index
		@rooms=Room.all
    end
end

app/helpers/bookrooms_helper.rb
module BookroomsHelper
end

app/views/admin/bookrooms/bill.html.erb
<div id="page-wrapper">
<div class="container-fluid" style="width:80%;">
    <div class="row">
        <div class="col-xs-12">
        	<div class="invoice-title">
    			<h2>Invoice</h2><h3 class="pull-right">Order # 12345</h3>
    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    				<strong>Billed To:</strong><br>
    					<%= @user.name %><br>
    					Da Nang<br>
    					VietNam<br>
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
        			<strong>From:</strong><br>
    					Plaza Hotel<br>
                        Lien Chieu- Da Nang<br>
    					Nguyen Luong Bang<br>
                        54
    					
    				</address>
    			</div>
    		</div>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    					<strong>Payment Method:</strong><br>
    					<%= @paymethod %><br>
    					*** 34445
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Order Date:</strong><br>
    					<%= Time.now %><br><br>
    				</address>
    			</div>
    		</div>
    	</div>
    </div>
    

    <div class="row">
    	<div class="col-md-12">
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title"><strong>Order summary</strong></h3>
    			</div>
    			<div class="panel-body">
    				<div class="table-responsive">
    					<table class="table table-condensed">
    						<thead>
                                <tr>
        							<td><strong>Item</strong></td>
        							<td class="text-center"><strong>Quantity</strong></td>
        							<td class="text-center"><strong>Per hours</strong></td>
                                    <td class="text-center"><strong>Hours</strong></td>
                                    <td class="text-center"><strong>VAT</strong></td>
        							<td class="text-right"><strong>Totals</strong></td>
                                </tr>
    						</thead>
    						<tbody>
    							<!-- foreach ($order->lineItems as $line) or some such thing here -->
                                <% @checkins.each do |c| %>
                                <% lineitem = get_corresspond_lineitem c.id %>
    							<tr>
    								<td><%= lineitem.room_code %></td>
                                    <td><%= lineitem.numberofperson %>
    								<td class="text-center"><%= m=(get_corresspond_roomtype lineitem.room_code).price %></td>
    								<td class="text-center"><%= t=get_time_booking lineitem.startdate, lineitem.fromdate %></td>
    								<td class="text-center">2.6%</td>
                                    <td class="text-right"><%= t*m %></td>
    							</tr>
                                <% end %>
    							<tr>
    								<td class="thick-line"></td>
    								<td class="thick-line"></td>
    								<td class="thick-line text-center"><strong>Subtotal</strong></td>
    								<td class="thick-line text-right">$670.99 Dong</td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Total</strong></td>
    								<td class="no-line text-right">$685.99 Dong</td>
    							</tr>
    						</tbody>
    					</table>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>
</div>

app/views/admin/bookrooms/checkout.html.erb
<div id="page-wrapper">
  <div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-2">
        
             <br>
            <!-- CREDIT CARD FORM STARTS HERE -->
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading display-table" >
                    <div class="row display-tr" >
                        <h3 class="panel-title display-td">Payment Details</h3>
                        <div class="display-td" >                            
                            <img class="img-responsive pull-right" src="http://i76.imgup.net/accepted_c22e0.png">
                        </div>
                    </div>                    
                </div>
                <div class="panel-body">
                     <%= form_tag({:controller => "bookrooms",:action => "bill"}) do %>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="cardNumber">PAY METHOD</label>
                                    <div class="input-group">           
                                       <%= select_tag :pay,"<option>Visa Card</option><option>Master Card</option><option>Deploma</option>option>MoMo</option>".html_safe,class: "form-control", id:"sel1"
                                        %>
                                        <span class="input-group-addon"></span>

                                    </div>
                                </div>                            
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="cardNumber">CARD NUMBER</label>
                                    <div class="input-group">
                                        <input 
                                            type="tel"
                                            class="form-control"
                                            name="cardNumber"
                                            placeholder="Valid Card Number"
                                            autocomplete="cc-number"
                                            required autofocus 
                                        />
                                        <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                    </div>
                                </div>                            
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-7 col-md-7">
                                <div class="form-group">
                                    <label for="cardExpiry"><span class="hidden-xs">EXPIRATION</span><span class="visible-xs-inline">EXP</span> DATE</label>
                                    <input 
                                        type="tel" 
                                        class="form-control" 
                                        name="cardExpiry"
                                        placeholder="MM / YY"
                                        autocomplete="cc-exp"
                                        required 
                                    />
                                </div>
                            </div>
                            <div class="col-xs-5 col-md-5 pull-right">
                                <div class="form-group">
                                    <label for="cardCVC">CV CODE</label>
                                    <input 
                                        type="tel" 
                                        class="form-control"
                                        name="cardCVC"
                                        placeholder="CVC"
                                        autocomplete="cc-csc"
                                        required
                                    />
                                </div>
                            </div>
                        </div>
                        <%= hidden_field_tag :user_id,@user_id %>
                        <div class="row">
                            <div class="col-xs-12">
                            <%= submit_tag("Get Bill",:class => "submit",:id => "SubmitTag",class: "subscribe btn btn-success btn-lg btn-block") %>
                            </div>
                        </div>
                        <% end %>
                        <div class="row" style="display:none;">
                            <div class="col-xs-12">
                                <p class="payment-errors"></p>
                            </div>
                        </div>
                </div>
            </div>            
            <!-- CREDIT CARD FORM ENDS HERE -->
            
            
        </div>  
      </div>
    </div>
</div>          
        

app/views/admin/bookrooms/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <tiles:insertAttribute name="content"></tiles:insertAttribute>
    <tiles:putAttribute name="content">
    <link href="/hanashop/templates/resource/datatable-bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="/hanashop/templates/resource/resources/datatable-responsive/css/dataTables.responsive.css" rel="stylesheet" />
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Danh sách check in</h1>
      </div>
    </div>
    
    <table class="table table-striped table-bordered table-hover" id="dataTables-dsSanPham">
      <thead>
        <tr>
          <th align="center">Booking id</th>
          <th align="center">Tên khách hàng</th>
          <th align="center">Số điện thoại</th>
          <th align="center">Số người ở</th>
          <th align="center">Tình trạng</th>
          <th align="center">Chi tiết</th>
          <th align="center">Action</th>
          <th align="center">Check out</th>
        </tr>
      </thead>
      <tbody id="tbl-body">
        <% i=0 %>
        <% @bookrooms.each do |b| %>
        <% 
          i=i+1      
          if b.pending? 
              icon_detail = "btn btn-info btn-lg"
              icon_checkout = "btn btn-default btn-lg"
              icon_remove = "btn btn-info btn-lg"
              icon_ok = "btn btn-info btn-lg"
              status_detail = false
              status_checkout = true
              status_remove = false
              status_ok = false
          elsif b.staying?
              icon_detail = "btn btn-info btn-lg"
              icon_checkout = "btn btn-info btn-lg"
              icon_remove = "btn btn-default btn-lg"
              icon_ok = "btn btn-default btn-lg"
              status_detail = false
              status_checkout = false
              status_remove = true
              status_ok = true
          else
              icon_detail = "btn btn-info btn-lg"
              icon_checkout = "btn btn-default btn-lg"
              icon_remove = "btn btn-default btn-lg"
              icon_ok = "btn btn-default btn-lg"
              status_detail = false
              status_checkout = true
              status_remove = true
              status_ok = true
          end
        %>

        <tr>
          <td align="center"><%= i %></td>
          <td align="center"><%= b.user.name %></td>
          <td align="center"><%= b.telephone %></td>
          <td align="center"><%= b.numberofperson %></td>
          <td align="center"><%= b.status %></td>
          <td text-align:center>
               <%= link_to admin_bookroom_path(b),class: icon_detail ,:disabled => status_detail do %>
                <span class="glyphicon glyphicon-zoom-in"></span>
               <% end %>
          </td>
          <td text-align:center>
             <%= link_to admin_checkout_path(:user_id => b.user.id),class: icon_remove ,:disabled => status_remove do %>
              <span class="glyphicon glyphicon-remove "></span>
             <% end %>
             <%= link_to admin_checkin_path(:user_id => b.user.id),class: icon_ok ,:disabled => status_ok do %>
              <span class="glyphicon glyphicon-ok-circle"></span>
             <% end %>
          </td>
          <td align="center">
             <%= link_to admin_checkout_path(:user_id => b.user.id),class: icon_checkout,:disabled => status_checkout do %>
              <span class="glyphicon glyphicon-arrow-right"></span>
             <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div align="center">
     <%= will_paginate %>
    </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
            <div class="modal-content">
              <form id="form-xoa"
              action=""
              method="post">
              <input id="modal-hidden-maSanPham" type="hidden" value=""
              name="maSanPham" />
              <div class="modal-header">
                <a href="#" data-dismiss="modal" aria-hidden="true" class="close">xóa</a>
                <h3>Xóa</h3>
              </div>
              <div class="modal-body">
                <p>Bạn có chắc chắn xóa thông tin này không?</p>
              </div>
              <div class="modal-footer">
                <button type="submit" id="btnYes" class="btn btn-danger">Có</button>
                <button type="button" data-dismiss="modal" aria-hidden="true"
                class="btn btn-secondary">Không</button>
              </div>
            </form>
          </div>
        </div>
      </div>


    </tiles:putAttribute>
    <tiles:putAttribute name="javascript-source">
    </tiles:putAttribute>
</tiles:insertTemplate>
</div>
</div>
</div>

app/views/admin/bookrooms/show.html.erb
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="headdings">
			<h3 class="ghj" align="center">Thông tin người đặt</h3>
			<div class="bs-example">
				<table class="table">
					<tbody>
						
						<tr>
							<td><h2 class="head" id="h2.-bootstrap-heading">Họ tên:<a class="anchorjs-link" href="#h2.-bootstrap-heading"></a></h2></td>

							<td><h2 class="head" id="h2.-bootstrap-heading">Nguyễn Văn <%= 
							@user.name %><a class="anchorjs-link" href="#h2.-bootstrap-heading"></h2></td>
							
						</tr>
						<tr>
							<td><h2 class="head" id="h2.-bootstrap-heading">Địa chỉ:<a class="anchorjs-link" href="#h2.-bootstrap-heading"></a></h2></td>

							<td><h2 class="head" id="h2.-bootstrap-heading">Quảng Nam<a class="anchorjs-link" href="#h2.-bootstrap-heading"></h2></td>
						</tr>
						
						
					</tbody>
				</table>
			</div>
		</div>	

        <h3 class="ghj" align="center">Thông tin phòng đặt</h3>
		<div class="appearance">
			<h3 class="ghj">B304</h3>
			<div class="col-md-12">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th width="50%">Tên</th>
							<th width="50%">Địa chỉ</th>
							<th width="50%">Chứng minh nhân dân</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Nguyễn Văn Lin</td>
							<td><span class="badge">TB-QN</span></td>
							<td><span class="badge">205671432</span></td>
						</tr>
						<tr>
							<td>Nguyễn Văn Lin</td>
							<td><span class="badge">TB-QN</span></td>
							<td><span class="badge">205671432</span></td>
						</tr>
						<tr>
							<td>Nguyễn Văn Lin</td>
							<td><span class="badge">TB-QN</span></td>
							<td><span class="badge">205671432</span></td>
						</tr>					
				   </tbody>
				</table>                    
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="appearance">
			<h3 class="ghj">B304</h3>
			<div class="col-md-12">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th width="50%">Tên</th>
							<th width="50%">Địa chỉ</th>
							<th width="50%">Chứng minh nhân dân</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Nguyễn Văn Lin</td>
							<td><span class="badge">TB-QN</span></td>
							<td><span class="badge">205671432</span></td>
						</tr>
						<tr>
							<td>Nguyễn Văn Lin</td>
							<td><span class="badge">TB-QN</span></td>
							<td><span class="badge">205671432</span></td>
						</tr>
						<tr>
							<td>Nguyễn Văn Lin</td>
							<td><span class="badge">TB-QN</span></td>
							<td><span class="badge">205671432</span></td>
						</tr>					
				   </tbody>
				</table>                    
			</div>
			<div class="clearfix"> </div>
		</div>
		
	</div>	
</div>