config/routes.rb
Rails.application.routes.draw do
   
  root 'pages#home'
  
  get 'sessions/new'

  get 'users/new'

  get 'users/index'

  get 'users/show'

  get '/sign_up', to: 'users#new'

  get '/login',to: 'sessions#new'

  post '/login',to: 'sessions#create'

  get '/logout',to: 'sessions#destroy'
  
  get '/about',to: 'pages#about'


  
  resources :checkins

  resources :users

  namespace :admin do
    resources :rooms
    resources :guests
    resources :bookrooms
    resources :roomtypes
    get '/bill',to: 'bookrooms#bill'
    post '/bill',to: 'bookrooms#bill'
    get '/checkout',to: 'bookrooms#checkout'
    get '/checkin',to: 'bookrooms#checkin'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :roomtype
  validates :room_code,  presence: true 
  mount_uploader :avatar, PictureUploader
end

app/models/roomtype.rb
class Roomtype < ApplicationRecord
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
    def new
      @room=Room.new
      @room_type=Roomtype.all.collect{|r| [r.name,r.id]} 
    end
    def create
       @room=Room.new (room_params)
       if @room.save
       	flash[:success]="Room created successfully"
       	redirect_to admin_rooms_path
       else
       	render 'new'
       end
    end
    def index
    	@rooms=Room.paginate(page: params[:page],per_page: 4)
    end

    def edit
    	@room=Room.find_by(id: params[:id])
    end
    def update
    	@room=Room.find_by(id: params[:id])
    	if @room.update_attributes(room_params)
    		flash[:success]="Room update successfully"
    		redirect_to admin_rooms_path
    	else
    		render 'edit'
    	end
    end
    def destroy
      Room.find(params[:id]).destroy
      redirect_to admin_rooms_path
    end

    private
    def room_params
    	params.require(:room).permit(:room_code,:bed_quantity,:roomtype_id,:avatar)
    end
end

app/views/admin/rooms/_form.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <tiles:putAttribute name="content">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= yield(:title) %></h1>
      </div>
    </div>

    <%= form_for [:admin,@room],html: {class: "form-horizontal",multipart: true} do |r| %>
       <%= render 'shared/error',object: @room %>
       <div class="form-group">
        <label class="col-lg-2 control-label">Tên phòng</label>
        <div class="col-lg-8">
           <%= r.text_field :room_code,class: "form-control input-medium" %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Số giường</label>
        <div class="col-lg-8">
           <%= r.text_field :bed_quantity,class: "form-control input-medium" %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label"> Loại Phòng</label>
        <div class="col-md-8">
          <%=r.select :roomtype_id,Roomtype.all.collect{|r| [r.name,r.id]},{prompt: '--Chọn kiểu phòng--'},{class:"form-control input-medium"} %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label">Picture</label>
         <div class="col-md-8">
          <%=r.file_field :avatar%>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label"></label>
        <div class="col-md-8">
          <%= r.submit yield(:button_text),class: "btn btn-primary" %>
          <span></span>
          <a href="" class="btn btn-default">Hủy</a>
        </div>
      </div>
    </form>
    <% end %>


  </tiles:putAttribute>

  <tiles:putAttribute name="javascript-source">
</tiles:putAttribute>

</tiles:insertTemplate>

</div>
</div>

</div>

app/views/admin/rooms/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <tiles:insertAttribute name="content"></tiles:insertAttribute>
    <tiles:putAttribute name="content">
    <link href="/hanashop/templates/resource/datatable-bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="/hanashop/templates/resource/resources/datatable-responsive/css/dataTables.responsive.css" rel="stylesheet" />
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Danh sách phòng</h1>
      </div>
    </div>
    <p>
      <%= link_to new_admin_room_path,class: "btn btn-success" do %>
        Thêm<i class="fa fa-plus"></i>
      <% end %>
    </p>
    <table class="table table-striped table-bordered table-hover" id="dataTables-dsSanPham">
      <thead>
        <tr>
          <th align="center">Name</th>
          <th align="center">Type</th>
          <th align="center">Số giường</th>
          <th align="center">Ảnh</th>
          <th align="center">Tình Trạng</th>
          <th align="center">Chức năng</th>
        </tr>
      </thead>
      <tbody id="tbl-body">
        <% @rooms.each do |r| %>
        <tr>
          <td align="center"><%= r.room_code %></td>
          <td align="center"><%= r.roomtype.name %></td>
          <td align="center"><%= r.bed_quantity %></td>
          <td align="center">
            <%= image_tag(r.avatar, size: "100x90") if r.avatar? %>
          </td>
          <td text-align:center>
            <img src="images/active.png" width="20" height="20" />
          </td>
          <td align="center">
             <input type="hidden" id="hidden-maSanPham" value="" />
             <%= link_to edit_admin_room_path(r),class: "btn btn-default" do %>
              <i class="fa fa-edit"></i>
             <% end %>
             <%= link_to admin_room_path(r), id: "btn-xoa",class: "btn btn-default",method: :delete,data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-remove"></i>
              <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div align="center">
     <%= will_paginate %>
    </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
            <div class="modal-content">
              <form id="form-xoa"
              action=""
              method="post">
              <input id="modal-hidden-maSanPham" type="hidden" value=""
              name="maSanPham" />
              <div class="modal-header">
                <a href="#" data-dismiss="modal" aria-hidden="true" class="close">xóa</a>
                <h3>Xóa</h3>
              </div>
              <div class="modal-body">
                <p>Bạn có chắc chắn xóa thông tin này không?</p>
              </div>
              <div class="modal-footer">
                <button type="submit" id="btnYes" class="btn btn-danger">Có</button>
                <button type="button" data-dismiss="modal" aria-hidden="true"
                class="btn btn-secondary">Không</button>
              </div>
            </form>
          </div>
        </div>
      </div>


    </tiles:putAttribute>
    <tiles:putAttribute name="javascript-source">
    </tiles:putAttribute>
</tiles:insertTemplate>
</div>
</div>
</div>

app/views/admin/rooms/new.html.erb
<% provide(:title,"Thêm thông tin phòng") %>
<% provide(:button_text,"Thêm") %>
<%= render 'form' %>