config/routes.rb
Rails.application.routes.draw do
   
  root 'pages#home'
  
  get 'sessions/new'

  get 'users/new'

  get 'users/index'

  get 'users/show'

  get '/sign_up', to: 'users#new'

  get '/login',to: 'sessions#new'

  post '/login',to: 'sessions#create'

  get '/logout',to: 'sessions#destroy'
  
  get '/about',to: 'pages#about'


  
  resources :checkins

  resources :users

  namespace :admin do
    resources :rooms
    resources :guests
    resources :bookrooms
    resources :roomtypes
    get '/bill',to: 'bookrooms#bill'
    post '/bill',to: 'bookrooms#bill'
    get '/checkout',to: 'bookrooms#checkout'
    get '/checkin',to: 'bookrooms#checkin'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
  has_many :lineitems,dependent: :destroy,:inverse_of => :checkin
  accepts_nested_attributes_for :lineitems,
  :reject_if => :all_blank, :allow_destroy => true

   enum status: [ :pending,:staying,:finish ]
  
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
	belongs_to :checkin
	has_many :lineitem_details, dependent: :destroy,:inverse_of => :lineitem
	accepts_nested_attributes_for :lineitem_details,
	:reject_if => :all_blank, :allow_destroy => true
end

app/models/lineitem_detail.rb
class LineitemDetail < ApplicationRecord
  belongs_to :lineitem 
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/permission.rb
class Permission < ApplicationRecord
	has_many :users
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :roomtype
  validates :room_code,  presence: true 
  mount_uploader :avatar, PictureUploader
end

app/models/roomtype.rb
class Roomtype < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	validates :name,presence: true,length: {maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,presence: true,length: {maximum:50},
	          format: {with: VALID_EMAIL_REGEX},
	          uniqueness: {case_sensitive: false }
	has_secure_password	

	belongs_to :permission
	has_many :checkins

	

end

app/controllers/bookrooms_controller.rb
class BookroomsController < ApplicationController
	def index
		@rooms=Room.all
    end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :logged_in_user, only: [:index, :create]
	def index
		@rooms=Room.all
  end
  def new
    	@checkin=current_user.checkins.build
    	@checkin.lineitems.build
    	#@lineitem_details=@lineitem.lineitem_details.build
    	@checkin.lineitems.each do |lineitem|
          lineitem.lineitem_details.build
      end
     	@room=Room.find_by(id: params[:room_id])
  end

  def create
      #khong phải là giải pháp cuối cùng =>
      #1,chưa thực hiện checkin bao giờ 
      #2.check in cuối cùng đã kết thúc
     
     #debugger
      #if  current_user.checkins.exists? && current_user.checkins.where("status = ?",0).exists?

          #current_check_in.lineitems.create checkin_params1
          # current_checkin=current_user.checkins.last
           #current_checkin.lineitems.create()
           

           # current_checkin.lineitems.create(room_code: params[:checkin][:lineitems_attributes]["0"][:room_code],
           #                   startdate: params[:checkin][:lineitems_attributes]["0"][:fromdate],
           #                   fromdate: params[:checkin][:lineitems_attributes]["0"][:fromdate])
          
          

           # n = params[:checkin][:lineitems_attributes]["0"][:lineitem_details_attributes].count
           # for i in 1..n

          #params[:checkin][:lineitems_attributes]["0"][:lineitem_details_attributes].each do |f| 
         
               
          #end


      #else
          @checkin =Checkin.create checkin_params
           # @checkin=current_user.checkins.last
           # @checkin.lineitems.create checkin_params1

     # end
       #debugger
       redirect_to checkins_path
       #end
  end

    private

    def checkin_params
       params.require(:checkin).permit(:telephone,:user_id,:description,
        lineitems_attributes:[:id,:room_code,:startdate,:fromdate,:numberofperson,
        lineitem_details_attributes:[:id,:nameguest,:identification,:address]])
       

     # debugger
    end

     def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end

    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def  home
	end
	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user=User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
         login user
         flash[:success]="Welcome to Plaza Hotel"
         if user.permission.role == 1
          redirect_to admin_rooms_path
         else
          redirect_to  checkins_path
         end 
  	else
  		flash[:danger]='Invalid emails/password '
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    	@users = User.paginate(page: params[:page])
    end

	def show
		@user=User.find(params[:id])
		@entries = @user.entries.paginate(page: params[:page])
	end

	def new
		@user=User.new
	end

	def create
		@user=User.new(user_params)
		@user.permission_id=6
		if @user.save
			login @user
			flash[:success] ="Welcome to the Plaza Hotel!"
			redirect_to checkins_path
		else
			render 'new'
		end
	end

	def edit
		@user=User.find(params[:id])
	end

    def update
    	@user=User.find(params[:id])
    	if @user.update_attributes(user_params)
    		flash[:success]="Profile updated"
    		redirect_to @user
    	else
    		render 'edit'
    	end
    end

    def user_params
	  	params.require(:user).permit(:name,:email,:password,
	  		:password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def hash_payment id
	  user=User.find_by_id(2)  
      hash_payment=Hash.new
       all_checkin=user.checkins
       all_checkin.each  do |checkin|
       hash_payment[:room_code]=checkin.lineitems.first.room_code
       hash_payment[:numberofperson]=3
       end     
    end
    def get_corresspond_lineitem id
        checkin=Checkin.find_by(id:id)
        checkin.lineitems.first
    end

    def get_corresspond_roomtype name
        room=Room.find_by(room_code:name)
        room.roomtype
    end

    def get_time_booking startdate,fromdate
        t=(fromdate - startdate)/3600
        t.to_i
    end
    def totalpay
    	
    end
     
end

app/helpers/bookrooms_helper.rb
module BookroomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# log in the given user
	def login(user)
		session[:user_id]=user.id
	end

	#Returns the current logged-in user
	def current_user
		@current_user ||=User.find_by(id: session[:user_id])
	end
    #check if user login
	def logged_in?
		!current_user.nil?
	end
    #logout out the current user
	def log_out
		session.delete(:user_id)
		@current_user=nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_ad_header.html.erb
<div id="wrapper">
  <nav class="navbar navbar-default navbar-static-top" role="navigation"
    style="margin-bottom: 0">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
    data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span> <span
    class="icon-bar"></span> <span class="icon-bar"></span> <span
    class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.php?view=admin">Admin</a>
    </div>

    <ul class="nav  navbar-right top-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li>
            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to logout_path,method: "delete" do %>
             <i class="fa fa-fw fa-power-off"></i>Log out
            <% end %>
          </li>
        </ul>
      </li>
    </ul>

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li><a href="#"><i class="fa fa-dashboard fa-fw"></i>
            Home</a></li>

            <li><a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>
              Quản lý loại phòng<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "Danh sách loại phòng",admin_roomtypes_path %></li>
                <li><%= link_to "Thêm loại phòng",new_admin_roomtype_path %></li>
              </ul> <!-- /.nav-second-level -->
            </li>

            <li><a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>
              Quản lý phòng<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "Danh sách phòng",admin_rooms_path %></li>
                <li><%= link_to "Thêm phòng",new_admin_room_path %></li>
              </ul> <!-- /.nav-second-level -->
            </li>

            <li><a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>
              Khách hàng<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><a href="#">Danh sách khách hàng</a></li>
                <li><a href="#">Thêm thể loại</a></li>
              </ul> <!-- /.nav-second-level -->
            </li>

            <li><a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>
              Đặt phòng<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "Danh sách đặt phòng",admin_bookrooms_path %></li>
                <li><a href="#">Tạo đơn hàng</a></li>
              </ul> <!-- /.nav-second-level -->
            </li>

            <li><a href="#" class="dropdown-toggle"
              data-toggle="dropdown"><i class="fa fa-bar-chart-o fa-fw"></i>
              Dịch vụ<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><a href="#">Danh sách dịch vụ</a></li>
                <li><a href="#">Loại dịch vụ</a></li>
              </ul> <!-- /.nav-second-level -->
            </li>

            <li><a href="#"><i class="fa fa-odnoklassniki fa-fw"></i>
              Nhân viên<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><a href="#">Danh sách nhân viên</a></li>
                <li><a href="#">Thêm nhân viên</a></li>
              </ul> <!-- /.nav-second-level -->
            </li>
        </ul>
      </div>
    </div>
 </nav>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
		<div class="container">
		<div class="touch-top heading">
				<h3>FOLLOW US</h3>
			</div>
			<div class="touch-bottom">
				<p>Nguyễn Lương Bằng,Đà Nẵng</p>
				<h6 >Phone: 0906227746</h6>
				<p>Email: hotel@gmail.com</p>
			</div>
			<div class="footer-top">
				<p class="footer-class">© 2015 Paix All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">.......</a> </p>
			</div>
		</div>
	   <a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	</div>
	<!--end-footer-->
</body>
</html>

app/views/layouts/_header.html.erb
	<div class="header" id="home">
		<div class="container">
			<div class="head">
			<div class="logo">
				<a href="index.html"><img src="" alt="" /></a>
			</div>
			<div class="navigation">
				 <span class="menu"></span> 
					<ul class="navig">
						<li><a href="index.html"  class="active hvr-bounce-to-bottom">Home</a></li>
						<li><%= link_to "About",about_path, class: "hvr-bounce-to-bottom" %></li>
						<li><a href="services.html" class="hvr-bounce-to-bottom">Services</a></li>
                        <% if logged_in? %>
						<li><%= link_to "Sign out",logout_path,method: "delete",class:"hvr-bounce-to-bottom" %></li>
						<% else %>
						<li><%= link_to "Sign in",login_path,class:"hvr-bounce-to-bottom" %>
						<% end %>				
						<li><%= link_to "Books room",checkins_path,class:"hvr-bounce-to-bottom" %>
						<li><a href="contact.html" class="hvr-bounce-to-bottom">Contact</a></li>
					</ul>
			</div>
				<div class="clearfix"></div>
			</div>
			</div>
	</div>	

	<!-- script-for-menu -->
	   <script>
			$("span.menu").click(function(){
				$(" ul.navig").slideToggle("slow" , function(){
				});
			});
		</script>
	<!-- script-for-menu -->
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelV4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true,'data-no-turbolink' => true  %>

  </head>

  <body data-no-turbolink="true">
    
    <% if logged_in? && current_user.permission.role == 1 %>
    <%= render 'layouts/ad_header' %>
    <% else %>
    <%= render 'layouts/header' %>
    <% end %>
    
    <div>
       <% flash.each do |message_type,message| %>
       <div><%= message %></div>
      <% end %>
    </div>

    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="about">
		<div class="container">
			<div class="about-top heading">
				<h3>ABOUT US</h3>
			</div>
			<div class="about-bottom">
				<p> Khách sạn Mithrin Hạ Long là khách sạn 4 sao đạt tiêu chuẩn quốc tế, chính thức đi vào hoạt động năm 2004.

Với 88 phòng khách có nội thất sang trọng, đầy đủ đồ dùng, trang trí ấm cúng, tao nhã cùng với cửa sổ rộng nhìn ra vịnh Hạ Long xinh đẹp, khách sạn Mithrin Hạ Long sẽ làm cho quý khách thực sự cảm thấy thoải mái, thuận tiện và hài lòng bởi tính chuyên nghiệp, mến khách và thân thiện của toàn thể nhân viên khách sạn.

Với sự yên tĩnh, dịch vụ tốt và vị trí thuận tiện, chỉ cách bến tầu du lịch khoảng 10 phút đi bộ và 10 phút đi xe tới khu công nghiệp Cái Lân, khách sạn Mithrin Hạ Long dần trở thành một địa chỉ tin cậy cho cả khách du lịch và khách thương gia tại trung tâm đang phát triển nhanh về du lịch của thành phố Hạ Long..</p>
				<div class="about-btm">
					<div class="col-md-6 about-left">
						<img src="images/abt-1.jpg" alt="" />
					</div>
					<div class="col-md-6 about-right">
						<img src="images/abt-2.jpg" alt="" />
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>

app/views/pages/home.html.erb
<script type="text/javascript">
   $(function() {
	   $( "#datepicker,#datepicker1" ).datepicker();
	});
</script>

<div class="banner">
		<div class="container">
			<div class="banner-top">
				<h1>For Booking</h1>
				<div class="banner-bottom">
					<div class="bnr-one">
						<div class="bnr-left">
							<p>From date</p>
						</div>
						<div class="bnr-right">
							<input class="date" id="datepicker1" type="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}" required=>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="bnr-one">
						<div class="bnr-left">
							<p>Ckeck Out</p>
						</div>
						<div class="bnr-right">
							<input class="date" id="datepicker1" type="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}" required=>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="bnr-one">
						<div class="bnr-left">
							<p>Adults</p>
						</div>
						<div class="bnr-right">
							<input type='number'></input>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="bnr-one">
						<div class="bnr-left">
							<p>Number of Room</p>
						</div>
						<div class="bnr-right">
							<select>
								<option value="volvo">Select a type</option>
								<option value="saab">Single</option>
								<option value="opel">Double</option>
								<option value="audi">Suite</option>
							</select>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="bnr-btn">
						<form>
							<input type="submit" value="Book Now">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script>
        $(function() {
        $( "#datepicker,#datepicker1" ).datepicker();
        });
      </script>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>